# Generated by Django 2.0.6 on 2018-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alex',
            name='slug',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alex',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
