# Generated by Django 2.0.6 on 2018-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180618_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alex',
            name='context',
        ),
        migrations.AddField(
            model_name='alex',
            name='content',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
